import type { Metadata } from "next";
import { Inter, Onest } from "next/font/google";
import "./globals.css";
import Layouts from "@/components/layouts/Layouts";

const inter = Inter({ subsets: ["latin"] });

const onest = Onest({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Curhatify",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={onest.className}>
        <Layouts>{children}</Layouts>
      </body>
    </html>
  );
}
